config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  get    'about'    => 'static_pages#about'

  match '*path' => 'application#routing_error', via: :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @tweet  = current_user.tweets.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def about
  end
end

app/views/static_pages/about.html.slim
<div class="well" style="text-align: center;">
	<h1>About</h1>
	<h2>NBA Project</h2>
	<p>Author: <a href="http://danieldvorkin.com">FDI Code Lab</a></p>
</div>

app/views/static_pages/home.html.slim
.row
  - if signed_in?
    - provide(:title, 'Home')
    aside.col-md-4
      section
        = render 'shared/user_info'

    div.col-md-8
      .timeline
        h2.title Tweets
        = render 'shared/feed'

  - else
    - provide(:title, 'Welcome')
    div.col-md-12.one-col
      h1 Welcome to NBA Project
      p Start a conversation, watch some highlights, make some new friends.

      = link_to 'Sign up', signup_path, class: "btn btn-primary"
      = link_to 'Sign in', signin_path, class: "btn btn-default"