config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  get    'about'    => 'static_pages#about'

  match '*path' => 'application#routing_error', via: :all
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .alert.alert-danger
    ul
      - object.errors.full_messages.each do |msg|
        li == msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.tweets
    = render partial: 'shared/feed_item', collection: @feed_items
  .paginate = will_paginate @feed_items, renderer: BootstrapPagination::Rails

app/views/shared/_feed_item.html.slim
li.tweet.clearfix id="#{feed_item.id}"
  = link_to gravatar_for(feed_item.user), feed_item.user
  .content
    .user = link_to feed_item.user.name, feed_item.user
    .tweet-content = wrap(feed_item.content)
    .tweet-footer
      Posted #{time_ago_in_words(feed_item.created_at)} ago.
      - if current_user?(feed_item.user)
        .tweet-actions = link_to "delete", feed_item, method: :delete,
                                                      data: { confirm: "You sure?" },
                                                      title: feed_item.content

app/views/shared/_follow.html.slim
= form_for(current_user.relationships.build(followed_id: @user.id)) do |f|
  div = f.hidden_field :followed_id
  = f.submit "Follow", class: "btn btn-large btn-primary"

app/views/shared/_follow_form.html.slim
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'shared/unfollow'
    - else
      = render 'shared/follow'

app/views/shared/_profile.html.slim
.profile.clearfix
  = link_to gravatar_for(@user, size: 52), @user
  div = link_to @user.name, @user
  div = @user.email
  = render 'shared/follow_form' if signed_in?

app/views/shared/_stats.html.slim
- @user ||= current_user

.stats
  table
    tr
      th Tweets
      th Followings
      th Followers
    tr
      td = link_to @user.tweets.count, user_path(@user)
      td = link_to @user.followed_users.count, following_user_path(@user)
      td = link_to @user.followers.count, followers_user_path(@user)

app/views/shared/_tweet_form.html.slim
.tweet-box
  = form_for(@tweet) do |f|
    = render 'shared/error_messages', object: f.object
    .field
      = f.text_area :content, placeholder: "New Post..."
    = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_unfollow.html.slim
= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f|
  = f.submit "Unfollow", class: "btn btn-large btn-default"

app/views/shared/_user_info.html.slim
- @user ||= current_user

= render 'shared/profile'
= render 'shared/stats'
= render 'shared/tweet_form'