config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :tweets,        only: [:index, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  get    'signup'   => 'users#new'
  get    'signin'   => 'sessions#new'
  delete 'signout'  => 'sessions#destroy'
  get    'about'    => 'static_pages#about'

  match '*path' => 'application#routing_error', via: :all
end

app/views/layouts/_footer.html.slim
hr

footer.footer
  = link_to "About ", about_path
  = " :: "
  = link_to "Contact"

app/views/layouts/_header.html.slim
.navbar.navbar-default.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      = link_to "NBAProject", root_path, class: "navbar-brand"
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar

    .navbar-collapse.collapse
      ul.nav.navbar-nav.navbar-right.header-menu
        - if signed_in?
          li
            = link_to users_path do
              = icon("users")
              span Users
          li
            = link_to user_path(current_user) do
              = icon("user")
              span Profile
          li
            = link_to tweets_path do
              = icon("comment")
              span All tweets
          li
            = link_to edit_user_path(current_user) do
              = icon("cog")
              span Settings
          li
            = link_to signout_path, method: "delete" do
              = icon("sign-out")
              span Sign out
        - else
          - unless params[:controller] == 'static_pages'
            li = link_to "Users",  users_path
            li = link_to "All tweets", tweets_path
            li = link_to "Sign In", signin_path

app/views/layouts/application.html.slim
doctype html

html
  head
    title = full_title(yield(:title))
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
      = yield
      = render 'layouts/footer'
      <hr/>
      